export interface ActionScrape {
  name: string;
  power: number;
  frames: number;
  maxUsage: number;
  className: string;
}

export const actionData: ActionScrape[] = [
  {
    name: 'ジュリーエンダンス（前半）',
    power: 202.8,
    frames: 45,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'ジュリーエンダンス（後半）',
    power: 274.5,
    frames: 124,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'アンチェインサークル（前半）',
    power: 577.2,
    frames: 64,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'アンチェインサークル（後半）',
    power: 202.8,
    frames: 35,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'クイックガッシュ（前半）',
    power: 441,
    frames: 92,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'クイックガッシュ（後半）',
    power: 259,
    frames: 53,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'スカイクライム（前半）',
    power: 207.5,
    frames: 43,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'スカイクライム（後半）',
    power: 227.5,
    frames: 47,
    maxUsage: 100,
    className: 'ファイター',
  },
  {
    name: 'フォトンブラスト（ダブルセイバー）',
    power: 3900,
    frames: 293,
    maxUsage: 1,
    className: 'ファイター',
  },
  {
    name: 'スパイラルドライブ（通常1派生）',
    power: 790,
    frames: 87,
    maxUsage: 2,
    className: 'ファイター',
  },
  {
    name: 'デッドリーアーチャー',
    power: 1596,
    frames: 180,
    maxUsage: 1,
    className: 'ファイター',
  },
  {
    name: 'スパイラルエッジ（ノンチャージ タイプ1）',
    power: 411,
    frames: 63,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（チャージ タイプ1）',
    power: 850,
    frames: 129,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（オーバーチャージ タイプ1）',
    power: 1700,
    frames: 267,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（オーバーチャージ+1秒 タイプ1）',
    power: 327,
    frames: 312,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（ノンチャージ タイプ2）',
    power: 411,
    frames: 63,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（チャージ タイプ2）',
    power: 978,
    frames: 146,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（オーバーチャージ タイプ2）',
    power: 1955,
    frames: 267,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スパイラルエッジ（オーバーチャージ+1秒 タイプ2）',
    power: 327,
    frames: 359,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'ツイストザッパー（ノンチャージ タイプ1）',
    power: 678,
    frames: 103,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ツイストザッパー（チャージ タイプ1）',
    power: 1060,
    frames: 163,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ツイストザッパー（オーバーチャージ タイプ1）',
    power: 2120,
    frames: 301,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ツイストザッパー（オーバーチャージ+1秒 タイプ1）',
    power: 361,
    frames: 352,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ツイストザッパー（ノンチャージ タイプ2）',
    power: 583,
    frames: 87,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'ストリークキャリバー（チャージ1段目 タイプ3）',
    power: 1184,
    frames: 160,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ2段目 タイプ3）',
    power: 1203,
    frames: 160,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ3段目 タイプ3）',
    power: 1314,
    frames: 172,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ1-3段 タイプ3）',
    power: 3700,
    frames: 492,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ1段目 タイプ1）',
    power: 746,
    frames: 98,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ2段目 タイプ1）',
    power: 758,
    frames: 98,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ3段目 タイプ1）',
    power: 828,
    frames: 107,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ1-3段 タイプ1）',
    power: 2331,
    frames: 303,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（チャージ1-3段 タイプ2）',
    power: 3976,
    frames: 492,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ストリークキャリバー（非チャージ1段+チャージ2-3段 タイプ2）',
    power: 2892,
    frames: 376,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'リレントレスクリーヴ（ノンチャージ 非カスタム）',
    power: 287,
    frames: 45,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'リレントレスクリーヴ（チャージ 非カスタム）',
    power: 910,
    frames: 135,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'リレントレスクリーヴ（オーバーチャージ 非カスタム）',
    power: 1820,
    frames: 273,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'リレントレスクリーヴ（オーバーチャージ+1秒 非カスタム）',
    power: 333,
    frames: 328,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'フォトンブラスト（ソード）',
    power: 4344,
    frames: 330,
    maxUsage: 1,
    className: 'ハンター',
  },

  {
    name: 'カッティングレイヤー（最速キャンセル タイプ2）',
    power: 443,
    frames: 78,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'カッティングレイヤー（全体 タイプ2）',
    power: 805,
    frames: 140,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'カッティングレイヤー（最速キャンセル タイプ1）',
    power: 372,
    frames: 72,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'カッティングレイヤー（全体 タイプ1）',
    power: 676,
    frames: 117,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'ヴェインミクスチャー（1回転 タイプ1）',
    power: 251,
    frames: 47,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヴェインミクスチャー（2回転 タイプ1）',
    power: 451,
    frames: 87,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヴェインミクスチャー（全体 タイプ1）',
    power: 835,
    frames: 149,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヴェインミクスチャー（全体→アンカー横全体 タイプ2）',
    power: 3917,
    frames: 667,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'タービュランストレイン（最速キャンセル タイプ3）',
    power: 313,
    frames: 59,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'タービュランストレイン（全体 タイプ3）',
    power: 580,
    frames: 106,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'タービュランストレイン（最速キャンセル タイプ1）',
    power: 251,
    frames: 49,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'タービュランストレイン（全体 タイプ1）',
    power: 464,
    frames: 86,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'ヘリッシュフォール（ノンチャージ 非カスタム）',
    power: 630,
    frames: 111,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヘリッシュフォール（チャージ 非カスタム）',
    power: 1145,
    frames: 375,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヘリッシュフォール（1秒で2回被弾）',
    power: 132,
    frames: 625,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヘリッシュフォール（2秒で2回被弾）',
    power: 192,
    frames: 429,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ヘリッシュフォール（3秒で2回被弾）',
    power: 252,
    frames: 327,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'ワイヤードアンカー（前）',
    power: 380,
    frames: 64,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ワイヤードアンカー（ニュートラル）',
    power: 185,
    frames: 45,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ワイヤードアンカー（後）',
    power: 270,
    frames: 51,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ワイヤードアンカー（横・最速）',
    power: 200,
    frames: 77,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'ワイヤードアンカー（横ホールド全体）',
    power: 2680,
    frames: 518,
    maxUsage: 100,
    className: 'ハンター',
  },

  { name: 'クロッシングフェザー', power: 1500, frames: 160, maxUsage: 1, className: 'ハンター' },
  { name: 'フォトンブラスト', power: 3972, frames: 271, maxUsage: 1, className: 'ハンター' },

  {
    name: 'サイズリッパー（ノンチャージ タイプ1）',
    power: 243,
    frames: 42,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'サイズリッパー（チャージ タイプ1）',
    power: 1080,
    frames: 161,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'サイズリッパー（チャージ前半 タイプ1）',
    power: 702,
    frames: 106,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'サイズリッパー（ノンチャージ タイプ2）',
    power: 243,
    frames: 42,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'サイズリッパー（チャージ タイプ2）',
    power: 956,
    frames: 157,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'サイズリッパー（チャージ前半 タイプ2）',
    power: 748,
    frames: 102,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'スタッブジャベリン（1hit+投擲 非カスタム）',
    power: 498,
    frames: 79,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（投擲のみ 非カスタム）',
    power: 415,
    frames: 79,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き3秒+投擲 非カスタム）',
    power: 1494,
    frames: 231,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き6秒+投擲 非カスタム）',
    power: 2822,
    frames: 414,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き9秒+投擲 非カスタム）',
    power: 4150,
    frames: 597,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き12秒+投擲 非カスタム）',
    power: 5478,
    frames: 777,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'スタッブジャベリン（1hit+投擲 タイプ1）',
    power: 398,
    frames: 68,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（投擲のみ タイプ1）',
    power: 332,
    frames: 68,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き3秒+投擲 タイプ1）',
    power: 1461,
    frames: 223,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き6秒+投擲 タイプ1）',
    power: 2855,
    frames: 408,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き9秒+投擲 タイプ1）',
    power: 4183,
    frames: 583,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き12秒+投擲 タイプ1）',
    power: 5578,
    frames: 768,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'スタッブジャベリン（1hit+投擲 タイプ2）',
    power: 540,
    frames: 79,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（投擲のみ タイプ2）',
    power: 523,
    frames: 79,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き3秒+投擲 タイプ2）',
    power: 739,
    frames: 231,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'スタッブジャベリン（1hit+投擲 タイプ3）',
    power: 448,
    frames: 79,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（投擲のみ タイプ3）',
    power: 374,
    frames: 79,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き3秒+投擲 タイプ3）',
    power: 1374,
    frames: 230,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き6秒+投擲 タイプ3）',
    power: 2809,
    frames: 407,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き9秒+投擲 タイプ3）',
    power: 4333,
    frames: 593,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'スタッブジャベリン（連続突き12秒+投擲 タイプ3）',
    power: 5767,
    frames: 769,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'フェイタルトルネード（ノンチャージ 非カスタム）',
    power: 763,
    frames: 118,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'フェイタルトルネード（チャージ 非カスタム）',
    power: 1330,
    frames: 197,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'トライアンフシフト（1段目まで タイプ3）',
    power: 288,
    frames: 42,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'トライアンフシフト（2段目まで タイプ3）',
    power: 588,
    frames: 86,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'トライアンフシフト（3段目まで タイプ3）',
    power: 990,
    frames: 147,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'トライアンフシフト（1段目まで タイプ1）',
    power: 245,
    frames: 35,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'トライアンフシフト（2段目まで タイプ1）',
    power: 500,
    frames: 72,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'トライアンフシフト（3段目まで タイプ1）',
    power: 842,
    frames: 124,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'トライアンフシフト（1段目まで タイプ2）',
    power: 288,
    frames: 42,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'トライアンフシフト（2段目まで タイプ2）',
    power: 550,
    frames: 80,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'トライアンフシフト（3段目まで タイプ2）',
    power: 955,
    frames: 141,
    maxUsage: 100,
    className: 'ハンター',
  },

  {
    name: 'アサルトチャージ（ノンチャージ）',
    power: 150,
    frames: 28,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'アサルトチャージ（チャージ）',
    power: 525,
    frames: 83,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'アサルトチャージ（ノンチャージ アナザー）',
    power: 375,
    frames: 70,
    maxUsage: 100,
    className: 'ハンター',
  },
  {
    name: 'アサルトチャージ（チャージ アナザー）',
    power: 1313,
    frames: 125,
    maxUsage: 100,
    className: 'ハンター',
  },
  { name: 'クイックアサルト', power: 400, frames: 57, maxUsage: 100, className: 'ハンター' },
  { name: 'フォトンブラスト', power: 4080, frames: 281, maxUsage: 1, className: 'ハンター' },
];
